### ISSUE TITLE
Changelog is missing information

### ISSUE THREAD

**Issue by shanethmoore** [zendesk/stronger_parameters#103]
Going through a rails upgrade in mobile services and not sure what stronger_parameters version is safe to use. Came across two issues in the changelog.

The (changelog.md)[https://github.com/zendesk/stronger_parameters/blob/master/Changelog.md#v260]
* Typo - 2.16.0 written as 2.6.0
* No details for for [2.17.0](https://rubygems.org/gems/stronger_parameters/versions/2.17.0)

_The ask: Can somebody make a PR updating the changelog with what was contained in 2.17.0?_

**Comment by grosser** [comment]
can you make the PR for 2.17 too ? :D

**Comment by shanethmoore** [comment]
I would if I was confident what the changes were 😅 

So far all I can tell is that the ruby version requirement has been bumped

**Comment by grosser** [comment]
idk what went in there ... could be just that :)

**Comment by fwilkens** [comment]
Done in https://github.com/zendesk/stronger_parameters/pull/114
