### ISSUE TITLE
 What would be the syntax to send an object?

### ISSUE THREAD

**Issue by FabianPinoPerez** [zendesk/stronger_parameters#120]
I am trying to send an object that is saved in my db as jsonb and in the documentation I do not see the syntax for this, please help me.

payload from postman

{
    "conversation":
        {
            "room_token": "dhskdhakhdak:akjhdksah111",
            "conversation_id": "slhcdkshd:ksdhckds111",
            "status": true,
            "archived": false,
            "assisted": true,
            "reactivated": false,
            "reactivated_at": "-4712-01-01T00:00:00.000Z",
            "language": "es",
            "labels": [
                "post-venta",
                "ventas"
            ],
            "custom": {
                "algo_custom": "custom"
            },
            "bot_id": 1,
            "lead_id": 1,
            "channel": 1,
            "page_id": "csmalmsals",
            "last_message": "ultimo mensaje"
        }
    }

**Comment by grosser** [comment]
I'd recommend parsing the jsonb first in a before_action and then sending into the validation so you can reuse the existing helpers
```
params[:payload] = JSON.parse(params[:payload])
... validate_params ...
```

but if you want to validate that it's json you could write a new json validator (that has to also use JSON.parse most likely)

**Comment by FabianPinoPerez** [comment]
thank you
