### ISSUE TITLE
Support type for decimals?

### ISSUE THREAD

**Issue by Aspoz** [zendesk/stronger_parameters#30]
I was wondering if there is any possibility to check for decimals? i tried floats but that doesn't quite work how i wanted to

**Comment by grosser** [comment]
You can build your own matcher to do whatever validation you want :)

**Comment by grosser** [comment]
This might be a good starting point:

https://github.com/zendesk/stronger_parameters/blob/master/lib/stronger_parameters/constraints/float_constraint.rb
