### ISSUE TITLE
Support type for hexadecimal input

### ISSUE THREAD

**Issue by jobertabma** [zendesk/stronger_parameters#37]
We verify tokens with a regular expression like `Parameters.regexp(/\A[a-f0-9]+\z/)`. Would people be interested in a `token` type that does that?

**Comment by grosser** [comment]
I don't think there is the generic token ... some have just letters/only lowercase/some dashes etc ... so maybe better to keep this a 1-off solution.

**Comment by jobertabma** [comment]
I agree. Renaming it to `hexadecimal` or `hexadecimal_string` would solve that though. Let me know if that makes sense. If so, I'll update this issue and get a PR out.

**Comment by grosser** [comment]
`.hex` could be good enough ... but then it would be a-f0-9 ... 
otherwise you can use `.alpha` for alphanumeric

**Comment by jobertabma** [comment]
Ugh, that is a typo. Thanks for your input, will get a PR out.

**Comment by pwen** [comment]
Nice! <3
