### ISSUE TITLE
Logical flaw in params parsing

### ISSUE THREAD

**Issue by Fodoj** [zendesk/stronger_parameters#4]
Let's say I have this setup:

```ruby
params.require(:user).permit(roles: Parameters.array(Parameters.string))
```

And then I send `{user: {roles: nil}}`.

Then it will go through stroger_params just fine, which is the same behaviour if I would send `{user: {}}`.

IMHO, if I send a param, then it must be validated according to what I wrote in controller. `nil` is not an array of strings => shall not pass.

Currently, if value is nil it just skips the param (https://github.com/zendesk/stronger_parameters/blob/master/lib/stronger_parameters/parameters.rb#L99).

What do you think?

**Comment by grosser** [comment]
@staugaard

**Comment by staugaard** [comment]
I agree.

**Comment by Fodoj** [comment]
@staugaard any plans to fix it or should I provide pull request then?

**Comment by grosser** [comment]
PR would be awesome :)

**Comment by Fodoj** [comment]
@grosser please review then :)
