### ISSUE TITLE
Exclusion of null bytes in Parameters.string

### ISSUE THREAD

**Issue by alexanderjeurissen** [zendesk/stronger_parameters#40]
When a nullbyte is present in the request parameters and the output of stronger parameters is directly used in a find_by for example an exception occurs stating that a nullbyte is present.

Replication steps:
```ruby
params[:test] = "hello\u0000"
clean_params = params.permit(test: Parameters.string)
User.find_by name: clean_params[:test] #  ArgumentError: string contains null byte
```

It would be nice if `Parameters.string` would strip nullbytes that way I don't have to `clean-params[:test].gsub("\u0000","")` everywhere.

I tried using negative lookahead with `Parameters.regexp` but with no avail.

```ruby
params.permit(test: Parameters.string & Parameters.regexp(/(?!.*\u0000.*)/))
```

**Comment by grosser** [comment]
Excluding null bytes by default seems a bit surprising to me ... having a
custom parameter should work fine though ...

```
class StringWithoutNull < StrongerParameters::String
  def value(v)
    string = super
    return StrongerParameters::InvalidValue.new("No nulls please") if
string.is_a?(String) && string.include?("\u0000")
    string
  end
end
```

**Comment by alexanderjeurissen** [comment]
@grosser Writing a custom parameter would require us to rewrite all places where we use `Parameters.string` you raise a valid point however that it is unexpected if null bytes are excluded by default.

Would you be open to receiving a PR where we add excluding null bytes as an option that can be passed to Parameters.String ? just like `max_length`

https://github.com/zendesk/stronger_parameters/blob/master/lib/stronger_parameters/constraints/string_constraint.rb

**Comment by grosser** [comment]
You can override Parameter.string to return your special version of string.

String is one of the base classes that is heavily used, so I'd prefer to
keep it lean, I'd think even the max/min should have been on a
'LimitedString' class or so ...

**Comment by esjee** [comment]
That's a good point @grosser. I think keeping the String class lean is definitely something to strive for.

In that case, how would you mix-and-match various String options?
For example, let's assume that the String class didn't support the min/max length arguments, but instead this was implemented using a `LimitedString`. In addition, let's say there's a `StringWithoutNull`. How would you combine this functionality?

I suppose I could do this by creating my own class `MyStrongerString`, which encapsulates both classes. That doesn't strike me as ideal however, and I wonder if there's a better solution.

@grosser @alexanderjeurissen What do you think?

**Comment by alexanderjeurissen** [comment]
@esjee Thanks for chiming in. I've put some more thought into this and I think that the argument for max/min doesn't really apply for null bytes seeing as excluding null bytes is a sane default, whilst min/max length is something that varies for different applications.

@grosser Can you give an example where not excluding null bytes in strings might be a valid use case ? I have trouble thinking of one seeing as the majority of the applications of stronger parameters directly use the output of stronger parameters in some sort of ActiveRecord query.

**Comment by grosser** [comment]
whenever binary data or strings with null bytes need to be submitted stripping null bytes would be bad ... and it's hard to bring it back once it was removed ... and adds the extra overhead that so far nobody needed (over how many years / apps this gem was already used in)

combining multiple traits should be easy with inheritance and each doing super + some check

```Ruby
class MinMaxString < String
class NullString < MinMaxString
```

**Comment by alexanderjeurissen** [comment]
@grosser Thanks for your patience, we discussed this internally and understand your motivation for not including this specific use-case. We'll maintain our own implementation for internal use.
