### ISSUE TITLE
PermittedParameters ControllerSupport Error

### ISSUE THREAD

**Issue by ianubhav** [zendesk/stronger_parameters#62]
When i include PermittedParameters I get uninitialized constant error

include StrongerParameters::ControllerSupport::PermittedParameters
NameError: uninitialized constant StrongerParameters::ControllerSupport::PermittedParameters
	from (irb):1

To resolve it I had to manually do 
require 'stronger_parameters/controller_support/permitted_parameters'

Shouldn't it be done automatically

**Comment by grosser** [comment]
yeah, can you make a PR to add it to https://github.com/zendesk/stronger_parameters/blob/master/lib/stronger_parameters.rb ?
