### ISSUE TITLE
Rails 5.2 support

### ISSUE THREAD

**Issue by richmolj** [zendesk/stronger_parameters#66]
The gemspec is preventing Rails 5.2, which was released yesterday https://github.com/zendesk/stronger_parameters/blob/master/stronger_parameters.gemspec#L27

I use this library in [JSONAPI Suite](https://jsonapi-suite.github.io/jsonapi_suite) as part of [Strong Resources](https://jsonapi-suite.github.io/jsonapi_suite/ruby/writes/strong-resources). I'd like to upgrade Suite to support 5.2 but blocked on this lib right now 🙂 Thanks for the great lib!

**Comment by richmolj** [comment]
I haven't been able to get the tests to run - looks like a minitest issue. I got [here](https://github.com/rails/rails/issues/31324#issuecomment-380130526) and [here](https://github.com/blowmage/minitest-rails/issues/209#issuecomment-356105328). If I remove minitest-rails there [won't be a superclass method for #get](https://github.com/zendesk/stronger_parameters/blob/master/test/stronger_parameters/controller_support/permitted_parameters_test.rb#L34).

I don't use minitest myself and I'm unfamiliar with your test suite, so that was my stopping point. I might eventually be able to get back to this.

**Comment by grosser** [comment]
https://github.com/zendesk/stronger_parameters/pull/67

**Comment by grosser** [comment]
2.10.1
