### ISSUE TITLE
 Option to return params as strings. 

### ISSUE THREAD

**Issue by bunufi** [zendesk/stronger_parameters#69]
To start with, thanks for this gem. Really enjoy simplicity and the ability to use permit method on params for validations. 

Currently I'm implementing Stronger Parameters in an existing API project that does not have any param validations. The project assumes that params object will return a set of strings, however stronger params casts the types. For this to work I have to convert every value back into the string. 

I do wonder what do you think about an option to get params back in strings. 
This would be consistent with the fact that rails stores param values as strings.

**Comment by grosser** [comment]
I'd rather not add that since it could be kinda confusing (in docs and in the docs) and is an edge-case ... I'd think what most users do is pass the params into AR objects and there string/object does not matter.

Something like this might do the trick ... but not sure if all .to_s produce exactly what was originally there:

```
def stringify_values!(hash)
  hash.each do |k, v|
    if v.is_a?(Hash)
      stringify_values!(v)
    elsif v.is_a?(Array)
      v.map! { |x| stringify_values!(x) }
   else
     hash[v] = k.to_s
  end
  hash
end
```

maybe as alternative keep a copy of the params and then call permit with just the keys ... either way it's going to be a it strange since stronger-parameters also does parsing when the original value was not strictly valid.

**Comment by bunufi** [comment]
Thanks for a quick reply. My first impulse was to convert all hash values to strings too. 
However, I have completely overlooked the fact that I can use Stronger Parameters to validate and still use `permit` method just as before to return the values that I need. Thanks for pointing that out. 

I have implemented Stronger Parameters in the following manner, to retain strings in params object and still have validations. This seems to be sufficient in our case. 

``` ruby
def validated_filters(raw_filters, allowed_filters, required_filters)
  return {} if raw_filters.blank?

  # Validation
  raw_filters.permit(allowed_filters).required(requires_filters)

  # Return params object with values as strings
  raw_filters.permit(allowed_filters.keys)
end
``` 
Confusing bit is the fact that permit is called twice on the same object with a slight difference which is not straightforward. 

Please feel free to close this issue. So far, I am happy with this implementation. Maybe it would be a good idea to mention this in the documentation, in case someone else cares about keeping params values as strings.

**Comment by grosser** [comment]
Thx for posting the update, the issue title is findable so I'd just close it until more people say they need this feature. Another alternative could be using a regex validations for cases where you want to retain strings.
