### ISSUE TITLE
BigInt and StrongerParameters

### ISSUE THREAD

**Issue by apanzerj** [zendesk/stronger_parameters#7]
Hey @staugaard 

Looks like we separate out int and bigint in stronger_parameters (https://github.com/zendesk/stronger_parameters/blob/f10a3832454b6db393404ae7a8e849814d673411/lib/stronger_parameters/parameters.rb#L58-L64). This is going to be problematic as once our ID space exceeds ```2**32``` we will need to say the ID is bigint OR int. What's a good fix for saying that Parameters.id can be ```0..2**64```? 

@grosser is adding BigNum support to the Parameters.integer which might be what we will end up doing in our code, rewriting Parameters.id to Parameters.integer.

@bquorning brought this up and we discussed this @grosser 

cc: @osheroff @ggrossman

**Comment by apanzerj** [comment]
and I just saw this a little lower:

https://github.com/zendesk/stronger_parameters/blob/f10a3832454b6db393404ae7a8e849814d673411/lib/stronger_parameters/parameters.rb#L62

d'oh! 

So we need to go through and replace "id" with "bigid"

**Comment by grosser** [comment]
other options
 - make .id = positive integer without restrictions and adding .small_id
for 32 bit
 - add id_size= accessor
