### ISSUE TITLE
NameError: uninitialized constant MyController::Parameters

### ISSUE THREAD

**Issue by mabdelfattah** [zendesk/stronger_parameters#71]
When I follow the documentation, I keep getting the following error:
`NameError: uninitialized constant MyController::Parameters`

But it works fine when I use `ActionController::Parameters` instead of `Parameters`

**Comment by grosser** [comment]
it's supposed to be made available via https://github.com/zendesk/stronger_parameters/blob/master/lib/stronger_parameters/parameters.rb#L181 so I'm thinking 
 - it's not in the Gemfile
- it's somehow not preloaded
 - the call that uses Parameters is before the preload

... `bundle open stronger_parameters` and put a `puts 'here'` into lib/stronger_parameters.rb

**Comment by momolog** [comment]
@mabdelfattah What was the solution here?
I am currently experiencing the same problem.
