### ISSUE TITLE
Rails 6 support

### ISSUE THREAD

**Issue by gencer** [zendesk/stronger_parameters#73]
Rails 6 RC1 Released. 6.1-devel started. Probably we will get stable version sooner. In the meantime, no notable changes will be made to Rails. Thus, we can start integrate it to dependencies which many dependencies already start include Rails 6.

Your `actionpack` requirement stops me from trying Rails 6.

**Comment by grosser** [comment]
can you make a PR that unlocks it and adds a rails v6 test ?

**Comment by gencer** [comment]
I can make a PR for this but one thing stops me.

In your `gemspecs`, you gave version numbers like `< 5.3`. As Rails 6 did not get released, we cannot use something like `< 6.1`. Is that correct? Also, I need to explicitly give `6.0.0.rc1` for gemfiles/rails6.0.gemfile.

Is that ok?

**Comment by grosser** [comment]
sounds good
